questions = [
  {"id": 0, "question": "I often feel a deep connection with the world around me.", "effects": {"expansive": 1}},
  {"id": 1, "question": "My thoughts are usually clear and focused.", "effects": {"focused": 1}},
  {"id": 2, "question": "I experience a sense of unity with nature and people.", "effects": {"expansive": 1}},
  {"id": 3, "question": "I find it easy to concentrate on specific tasks.", "effects": {"focused": 1}},
  {"id": 4, "question": "I feel most awake when I am deeply connected to my surroundings.", "effects": {"expansive": 1}},
  {"id": 5, "question": "Clarity of thought is a significant aspect of my wakefulness.", "effects": {"focused": 1}},
  {"id": 6, "question": "I often find myself lost in the beauty of the world.", "effects": {"expansive": 1}},
  {"id": 7, "question": "My best moments of wakefulness come when I am deeply absorbed in a task.", "effects": {"focused": 1}},
  {"id": 8, "question": "I feel a sense of expansiveness in my awareness.", "effects": {"expansive": 1}},
  {"id": 9, "question": "Focused and insightful thinking defines my experience of wakefulness.", "effects": {"focused": 1}},
  {"id": 10, "question": "My sense of wakefulness is consistent and stable.", "effects": {"stable": 1}},
  {"id": 11, "question": "I experience fluctuations in my state of wakefulness.", "effects": {"variable": 1}},
  {"id": 12, "question": "I can maintain a wakeful state for extended periods.", "effects": {"stable": 1}},
  {"id": 13, "question": "My experience of wakefulness comes and goes.", "effects": {"variable": 1}},
  {"id": 14, "question": "I have a steady and unwavering sense of awareness.", "effects": {"stable": 1}},
  {"id": 15, "question": "There are moments when I feel more awake, followed by periods of less awareness.", "effects": {"variable": 1}},
  {"id": 16, "question": "My state of wakefulness does not change much from day to day.", "effects": {"stable": 1}},
  {"id": 17, "question": "I notice significant variations in my sense of wakefulness.", "effects": {"variable": 1}},
  {"id": 18, "question": "I have a stable baseline of wakefulness.", "effects": {"stable": 1}},
  {"id": 19, "question": "My wakefulness can be intense at times and subdued at other times.", "effects": {"variable": 1}},
  {"id": 20, "question": "I find stability in my expansive awareness.", "effects": {"upperLeft": 1}},
  {"id": 21, "question": "My focused insight tends to be variable and fluctuating.", "effects": {"lowerRight": 1}},
  {"id": 22, "question": "My clarity of thought is a constant in my life.", "effects": {"upperRight": 1}},
  {"id": 23, "question": "I experience waves of feeling connected to the world around me.", "effects": {"lowerLeft": 1}},
  {"id": 24, "question": "I have stable moments of unity with nature and people.", "effects": {"upperLeft": 1}},
  {"id": 25, "question": "My ability to concentrate deeply varies from time to time.", "effects": {"lowerRight": 1}},
  {"id": 26, "question": "I maintain a consistent sense of clarity in my thoughts.", "effects": {"upperRight": 1}},
  {"id": 27, "question": "My sense of connection with the external world fluctuates.", "effects": {"lowerLeft": 1}},
  {"id": 28, "question": "I find a steady sense of unity in my expansive awareness.", "effects": {"upperLeft": 1}},
  {"id": 29, "question": "My focused insight can be intense but is not always consistent.", "effects": {"lowerRight": 1}},
  {"id": 30, "question": "I feel a sense of aliveness and vitality in my daily life.", "effects": {"general": 1}},
  {"id": 31, "question": "There are moments when I feel more connected to the world than usual.", "effects": {"general": 1}},
  {"id": 32, "question": "I often experience a state of inner stillness and peace.", "effects": {"general": 1}},
  {"id": 33, "question": "My awareness of the present moment is heightened.", "effects": {"general": 1}},
  {"id": 34, "question": "I feel a sense of clarity in my understanding of the world.", "effects": {"general": 1}},
  {"id": 35, "question": "There are times when I feel detached from my thoughts and emotions.", "effects": {"general": 1}},
  {"id": 36, "question": "I often find myself in a state of flow, completely absorbed in what I am doing.", "effects": {"general": 1}},
  {"id": 37, "question": "I feel a deep sense of peace and tranquility.", "effects": {"general": 1}},
  {"id": 38, "question": "I am able to maintain a sense of awareness throughout the day.", "effects": {"general": 1}},
  {"id": 39, "question": "I feel a strong sense of connection to the present moment.", "effects": {"general": 1}},
];
